schema_version: 1

context:
  version: "0.66b1"

package:
  name: opentelemetry-exporter-otlp-common
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/o/opentelemetry-exporter-otlp-common/opentelemetry_exporter_otlp_common-${{ version }}.tar.gz
  sha256: 6b1403487a2185ac1feb45fd5546fdf8630ce71c36bcefaadf51e2130e9e23f9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - opentelemetry-sdk 1.45.*

tests:
  - python:
      imports:
        - opentelemetry.exporter.otlp.common
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: OpenTelemetry OTLP HTTP export utilities
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-common

extra:
  recipe-maintainers:
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-sdk
    - xhochy
